vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        listing_file:
            uri_prefix: /uploads/listing
            upload_destination: "%upload_directory%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
